# Generated by Django 3.2.5 on 2021-10-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lastActivity',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
