# Generated by Django 3.2.5 on 2021-10-04 20:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customuser_lastactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastActivity',
            field=models.IntegerField(null=True),
        ),
    ]
